[build-system]
requires = ["setuptools>=75.0.0", "cython>3.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["cythontesting"]

[project]
name        = "cythontesting"
version     = "0.0.1"